import httpx
import time
import json

API_BASE = "http://localhost:8005/api/v1"

def test_phase2_flow():
    print("=== 1. Testing Health and Baseline Fitting ===")
    h_res = httpx.get(f"{API_BASE}/health")
    assert h_res.status_code == 200
    print("Health Status:", h_res.json())

    print("\n=== 2. Testing Stream Ingestion with Phase 2 Fusion Detection ===")
    complex_anomaly_record = {
        "survey_code": "PLFS_2024",
        "survey_round": "2024-25",
        "state_code": "27",
        "district_code": "005",
        "sector": "2",
        "fsu_id": "FSU27005_DEMO",
        "raw_payload": {
            "Survey_Round": "2024-25",
            "State": "27",
            "District": "005",
            "Sector": "2",
            "Hh_No": 14,
            "Person_No": 1,
            "Rel_To_Head": 1,
            "Sex": 1,
            "Age": 14, # Rule Violation: Age < 15
            "General_Edu": 12, # Rule Violation: Age 14 is Graduate
            "Usual_Principal_Activity_Status": 31, # Rule Violation: Age 14 is Regular Salaried
            "Earnings_Last_Month": 450000.0, # Statistical Outlier & ML Outlier
            "Daily_Wages": 18000.0, # Statistical Outlier & ML Outlier
            "Monthly_Exp": 150000.0,
            "Multiplier": 350.0
        }
    }

    r_stream = httpx.post(f"{API_BASE}/records/ingest/stream", json=complex_anomaly_record, timeout=30.0)
    assert r_stream.status_code == 200
    res = r_stream.json()

    print("Stream Detection Summary:")
    det_sum = res["detection_summary"]
    print(f"Overall Risk Score: {det_sum['overall_risk']} / 100")
    print(f"Risk Band: {det_sum['risk_band']}")
    print(f"Detectors Fired: {det_sum['detectors_fired']}")
    print(f"Detector Agreement Count: {det_sum['detector_agreement_count']}")
    print("\nNarrative Bullets Generated by EvidenceComposer:")
    for bullet in det_sum["narrative_bullets"]:
        print(" -", bullet.encode("ascii", errors="ignore").decode("ascii"))

    assert det_sum["overall_risk"] >= 50
    assert det_sum["risk_band"] in ("REVIEW", "HIGH_PRIORITY")
    assert len(det_sum["narrative_bullets"]) >= 3

    print("\n=== 3. Testing Batch Ingestion with Phase 2 Pipeline ===")
    with open("data/plfs_microdata.csv", "rb") as f:
        r_batch = httpx.post(f"{API_BASE}/records/ingest/batch", files={"file": ("plfs_microdata.csv", f, "text/csv")})
    
    assert r_batch.status_code == 200
    job_id = r_batch.json()["job_id"]
    print(f"Batch Job Submitted. ID: {job_id}")

    for _ in range(20):
        job_info = httpx.get(f"{API_BASE}/jobs/{job_id}").json()
        if job_info["status"] in ("completed", "failed"):
            break
        time.sleep(0.5)

    print(f"Batch Job Completed: {job_info['status']} | Processed: {job_info['processed_records']} | Flags: {job_info['flag_count']}")
    assert job_info["status"] == "completed"

    print("\n=== 4. Querying Multi-Detector Anomaly Flags ===")
    r_flags = httpx.get(f"{API_BASE}/flags")
    assert r_flags.status_code == 200
    flags_data = r_flags.json()

    print(f"Total Flags in DB: {flags_data['total']}")
    assert flags_data['total'] > 0

    sample_flag = flags_data["flags"][0]
    print("\nSample Flag Evidence Payload Structure:")
    print("Detector Type:", sample_flag["detector_type"])
    print("Severity:", sample_flag["severity"])
    print("Score:", sample_flag["score"])
    print("Detectors Fired in Evidence:", sample_flag["evidence"].get("detectors_fired"))
    print("Narrative Bullets:")
    for b in sample_flag["evidence"].get("narrative_bullets", []):
        print("   *", b.encode("ascii", errors="ignore").decode("ascii"))

    print("\nALL PHASE 2 CORE INTELLIGENCE TESTS PASSED SUCCESSFULLY!")

if __name__ == "__main__":
    test_phase2_flow()
